---
- name: Get info from UCS
  hosts: ucs
  connection: local
  gather_facts: no

  tasks: 
    - name: Pull WWPNs from UCS
      getucswwpns:
        host={{ inventory_hostname }}
        ucs_user={{ username }}
        ucs_pass={{ password }}
        outputfile=./output/wwpn.json

- name: Generate SAN Zones
  hosts: nexus5k
  connection: local
  gather_facts: no

  tasks:
    - name: Generate Fibre Channel zone configuration
      generatefczones: 
        host={{ inventory_hostname }}
        fabric_id={{ fabricid }}
        vsan_id={{ vsanid }}
        fc_targets={{ targets }}
        inputfile=./output/wwpn.json
        zonefile_fabric_a=./output/zonecfg_a.txt
        zonefile_fabric_b=./output/zonecfg_b.txt

# - name: Perform SAN Configuration
#   hosts: nexus5k
#   connection: local
#   gather_facts: no

#   tasks:
#     - name: Push configuration to Nexus switches via SSH
#       installfczones: 
#         host={{ inventory_hostname }}
#         n5k_user={{ username }}
#         n5k_pass={{ password }}
#         fabric_id={{ fabricid }}
#         logfile=../output/log.txt
#         zonefile_fabric_a=../output/zonecfg_a.txt
#         zonefile_fabric_b=../output/zonecfg_b.txt