---
- name: Get Existing UCS Information
  hosts: ucs
  connection: local
  gather_facts: no

  tasks: 
    - name: Pull WWPNs from UCS
      getucswwpns:
        host={{ inventory_hostname }}
        ucs_user={{ username }}
        ucs_pass={{ password }}
        outputfile=output.txt
        logfile=log.txt

- name: Perform SAN Configuration
  hosts: nexus5k
  connection: local
  gather_facts: no

  tasks:
    - name: Push configuration to Nexus switches via SSH
      installconfig: 
        host={{ inventory_hostname }}
        n5k_user={{ username }}
        n5k_pass={{ password }}
        fabric_id={{ fabricid }}
        vsan_id={{ vsanid }}
        fc_targets={{ targets }}
        inputfile=output.txt
        logfile=log.txt